<?php

/**
 * Implements alter_site_info_theme().
 * 
 * Adds twig template for presenting information page.
 * 
 */
function alter_site_info_theme($existing, $type, $theme, $path) {

  return [
    'alter_site_info_json_page' => [
      'render element' => 'children',
      'template' => 'alter-site-info-json-page',
      'path' => $path . '/templates',
      'variables' => [
        'apikey' => '',
        'nid' => '',
        'node' => ''
      ],
    ],
  ];

} 
